// <auto-generated />
using System;
using AmnilTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmnilTest.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190109172149_seed data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmnilTest.Model.Contestant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int>("DistrictId");

                    b.Property<string>("Firstname")
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Lastname")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Contestant");

                    b.HasData(
                        new { Id = 1, Address = "Kathmandu", DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), DistrictId = 1, Firstname = "Nischhal", Gender = "Male", IsActive = false, Lastname = "Shrestha" },
                        new { Id = 2, Address = "Lalitpur", DateOfBirth = new DateTime(1976, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), DistrictId = 2, Firstname = "Ram", Gender = "Male", IsActive = false, Lastname = "Shrestha" },
                        new { Id = 3, Address = "Kaski", DateOfBirth = new DateTime(1960, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), DistrictId = 3, Firstname = "Sita", Gender = "Male", IsActive = false, Lastname = "Malla" }
                    );
                });

            modelBuilder.Entity("AmnilTest.Model.ContestantRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContestantId");

                    b.Property<DateTime>("RatedDate");

                    b.Property<int>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("ContestantId");

                    b.ToTable("ContestantRating");
                });

            modelBuilder.Entity("AmnilTest.Model.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("District");

                    b.HasData(
                        new { Id = 1, Name = "Kathmandu" },
                        new { Id = 2, Name = "Lalitpur" },
                        new { Id = 3, Name = "Kaski" }
                    );
                });

            modelBuilder.Entity("AmnilTest.Model.Contestant", b =>
                {
                    b.HasOne("AmnilTest.Model.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AmnilTest.Model.ContestantRating", b =>
                {
                    b.HasOne("AmnilTest.Model.Contestant", "Contestant")
                        .WithMany()
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
